Resources:
  TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      # StreamSpecification:
      #   StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Name
          Value: entities-table
